### PR TITLE
Load packages in parallel.

### PR DESCRIPTION
**Pull request by joelburget**
When running the [rhino-hawk demo](https://x80.org/rhino-hawk/) I see a bad dependency cascade as each package is downloaded in sequence. I think `map_p` should fix this. Disclaimer: unfortunately this change is untested since I can't build successfully.

screen shot 2018-03-18 at 3 56 23 pm

### CODE REVIEW

**Comment by ejgallego** [comment]
Thanks for the report @joelburget !

The original choice was motivated because in jscoq you have "two level packages", for example, the mathcomp library is the `mathcomp` package that contains about 50 smaller units. Top level packages are downloaded in parallel, the smaller ones are downloaded sequentially as I was not sure launching 100 downloads simultaneously would be a good idea. [For example the original code was also doing some CPU expensive stuff such as md5 summing with each package].

I'll push the change to SerAPI ASAP, your input is very appreciatted as I have close-to-zero frontend experience. Also note that I am actually going to split the package manager to its own repository to it can be shared among jscoq/serapi and used if desired by third parties. This should also brings us some flexibility as to better adapt it to front-end use cases.

Regarding the building issue, please let me know if I can be of help, I'll be glad to. I tend to be around Gitter [modulo meetings/classes] so feel free to ping me there.

**Comment by ejgallego** [comment]
Hi @joelburget , sorry for the long delay; what is the status of this PR? I see many unrelated changes stacked here.

**Comment by joelburget** [comment]
Hi @ejgallego, I think that I must have force-pushed to my v8.8 branch sometime after opening this so it no longer does what it says.

**Comment by ejgallego** [comment]
Hi @joelburget , thanks a lot; note that I would still like to improve this setup; but I need to perform some other refactoring wrt to packages first; if this would still be useful to you please open an issue as a reminder.

**Pull request closed without merging**
