### PR TITLE
[sercomp] sertok program for batch tokenization

### PR DESCRIPTION
**Pull request by palmskog**
This is rudimentary but may at least convey the general idea of what we need in terms of batch tokenization.

There are two fundamental problems right now that I don't know how to solve due to lack of API knowledge:

1. how to get the raw string from a sentence read from a stream
2. how to get serialization to print the locs as in `sertop`

Could you take a look and give some pointers @ejgallego?

### CODE REVIEW

**Comment by ejgallego** [comment]
I'll try to look into this ASAP.

**Comment by palmskog** [comment]
For reference, the output currently looks like:
```
(IDENT Require)
 (IDENT Import)
 (IDENT List)
 (KEYWORD .)
 EOI
```
And ideally it would look something like:
```
((v(VernacExpr()(((v(IDENT Require))(loc(((fname(InFile test.v))(line_nb 1)(bol_pos 0)(line_nb_last 1)(bol_pos_last 0)(bp 0)(ep 7)))))((v(IDENT Import))(loc(((fname(InFile test.v))(line_nb 1)(bol_pos 0)(line_nb_last 1)(bol_pos_last 0)(bp 8)(ep 14)))))((v(IDENT List))(loc(((fname(InFile test.v))(line_nb 1)(bol_pos 0)(line_nb_last 1)(bol_pos_last 0)(bp 15)(ep 19)))))((v(KEYWORD .))(loc(((fname(InFile test.v))(line_nb 1)(bol_pos 0)(line_nb_last 1)(bol_pos_last 0)(bp 19)(ep 20)))))((v EOI)(loc(((fname(InFile test.v))(line_nb 1)(bol_pos 0)(line_nb_last 1)(bol_pos_last 0)(bp 20)(ep 21)))))))))
```

**Comment by ejgallego** [comment]
> And ideally it would look something like:

Why `vernacexpr` ?

**Comment by palmskog** [comment]
> Why `vernacexpr` ?

We decided to split tokenization at the sentence level, since it then becomes easy to combine AST and token information. We could call it "sentence" if you prefer, but some marker would be nice.

**Comment by ejgallego** [comment]
> 2\. how to get serialization to print the locs as in `sertop`

IIUC you need to wrap the tokens into a `CAst.t` or into a `Loc.located` node, as you prefer. [First is recommended], then you just use the `CAst` serializers.

> 1. how to get the raw string from a sentence read from a stream

I need to look more, but likely the API is not general enough, as the "STM" won't allow you to use `parse_token_stream` ; you could override the STM for batch use and just hook to `Vernacentries` directly [not the worst idea in fact] , patch the API [a bit late for 8.10] or just peek the stream / keep a copy of it and split once you get the location information.

**Comment by ejgallego** [comment]
> We could call it "sentence" if you prefer, but some marker would be nice.

Ah, sounds good; I got confused with the actual marker for VernacExpr.

**Comment by palmskog** [comment]
> IIUC you need to wrap the tokens into a CAst.t or into a Loc.located node, as you prefer. [..]  then you just use the CAst serializers.
Yes, I already copied some boilerplate of yours to do the wrapping, but I don't know the proper idiom for calling serializers+printers on something of type `Tok.t CAst.t list`.

**Comment by ejgallego** [comment]
Should be something such as `sexp_of_list (CAst.sexp_of_t Tok.sexp_of_t)` provided you open `Sepxlib` and `Serlib`

You can also do
```
type tlist = Tok.t CAst.t list [@@deriving sexp]
```
And have it generated for you.

**Comment by palmskog** [comment]
To avoid hacking Coq and just get something that works for now, I use the `Loc.t` for an AST to look up the string to tokenize in the source file. It seems to work after adjusting offsets. Example:
```
(Sentence
 (((v(IDENT Require))(loc(((fname(InFile test.v))(line_nb 1)(bol_pos 0)(line_nb_last 1)(bol_pos_last 0)(bp 0)(ep 7)))))
  ((v(IDENT Import))(loc(((fname(InFile test.v))(line_nb 1)(bol_pos 0)(line_nb_last 1)(bol_pos_last 0)(bp 8)(ep 14)))))
  ((v(IDENT List))(loc(((fname(InFile test.v))(line_nb 1)(bol_pos 0)(line_nb_last 1)(bol_pos_last 0)(bp 15)(ep 19)))))
  ((v(KEYWORD .))(loc(((fname(InFile test.v))(line_nb 1)(bol_pos 0)(line_nb_last 1)(bol_pos_last 0)(bp 19)(ep 20)))))))
```

**Comment by ejgallego** [comment]
Looks good indeed.

The current parsing situation in Coq is a bit tricky so this may be the way you want to go for now.

**Comment by ejgallego** [comment]
@palmskog I see this still has the `in-progress` tag, and likely the commits could use some squashing / commit message tweaks, right? Please let me know when you think is ready for merge and I'll review.

I think the main task I'd like to do before merging is to extract an specification from this program and open a ticket upstream so parsing does expose tokenization in a more convenient way.

**Comment by ejgallego** [comment]
I'd like to ship this in the 8.10 release, let me know if I can take the lock or you would like to do a pass before.

**Comment by palmskog** [comment]
I think the content of this PR is ready for your review now @ejgallego. If you want me to "refactor" the commits, maybe you can give some hint about the granularity you want, e.g., one commit for the program and one for the documentation?

**Comment by ejgallego** [comment]
> I think the content of this PR is ready for your review now @ejgallego. If you want me to "refactor" the commits, maybe you can give some hint about the granularity you want, e.g., one commit for the program and one for the documentation?

Thanks @palmskog ,I think commits are fine like this, you can squash maybe a couple if you want (2nd with 1st and 5th with 4th?), but otherwise I'll keep it this way. If you do, you could also add a `[sertok]` header to the commits, I dunno why but it makes reading the commit log clearer for me.

**Comment by ejgallego** [comment]
BTW, should you remove the `in-progress` tag?

**Comment by palmskog** [comment]
@ejgallego I squashed and changed commit messages according to your advice. The `in-progress` tag is also gone now.

**Comment by ejgallego** [comment]
Great thanks! Hopefully I can process all the remaining PRs in a few days.

**Pull request merged**
