### PR TITLE
[serlib] Fix ssr serialization test (cc #68)

### PR DESCRIPTION
**Pull request by ejgallego**
This requires a patch to Coq upstream, so it will have to wait for merge of

- v8.9: https://github.com/coq/coq/pull/9071

This PR is the 8.9 version, for the v8.10 see #115

### CODE REVIEW

**Comment by ejgallego** [comment]
`v8.10` PR has been already merged upstream, hoping we can get 8.9 PR in.

**Comment by ejgallego** [comment]
Update to cover latest tests. CI will presumably fail.

**Comment by ejgallego** [comment]
Updated.

**Comment by ejgallego** [comment]
Let's be optimistic and hope that this can be fixed in 8.9.1 :(

**Comment by ejgallego** [comment]
I am repurposing this 8.10 as 8.9.1 is uncertain; we can always backport the change if v8.9 [coq/coq#9071](https://github.com/coq/coq/pull/9071) is ever merged.

**Comment by ejgallego** [comment]
> I am repurposing this 8.10 as 8.9.1 is uncertain; we can always backport the change if v8.9 [coq/coq#9071](https://github.com/coq/coq/pull/9071) is ever merged.

Ok taking back my choice as this alter users of the branch, this PR is 8.9-only, and a new PR has been opened at #115 for 8.10

**Comment by ejgallego** [comment]
Not gonna happen.

**Comment by palmskog** [comment]
Please keep this branch available for now.

**Pull request closed without merging**
