### PR TITLE
[coq] support for Coq 8.13

### LINKED ISSUE #227: Support for 8.13?
We're using Alectryon which depends on this.

### PR DESCRIPTION
**Pull request by ejgallego**
Changes are quite manageable, as we expect from a regular release
process; main problem that prevented this from being automatic is the
extended use of GADT's in Coq's side, which are not supported by our
serializers [hard problem].

Protocol is almost untouched, except for:

- Case term representation has changed upstream [new caseinvert field]
- Proof state removed `shelf` and `given_up` fields [see .mli files]
- A few minor tweaks on the AST of Tactics and commands

Closes #227

### CODE REVIEW

**Comment by jhaag** [comment]
Is there a timeline in place for addressing the remaining TODOs which are pending for this PR?

Looking ahead, is this sort of breakage/turn-around common for serapi or was there a particular Coq change/extenuating circumstance which resulted in this lengthy delay between the 8.13 release and the (eventual) serapi bump?

**Comment by ejgallego** [comment]
> Is there a timeline in place for addressing the remaining TODOs which are pending for this PR?
> 
> Looking ahead, is this sort of breakage/turn-around common for serapi or was there a particular Coq change/extenuating circumstance which resulted in this lengthy delay between the 8.13 release and the (eventual) serapi bump?

As of now there is nothing too particular, usually porting serapi happens when I have the time to do it, and so far it didn't require a lot of time, but my January for example was quite busy.

We could add SerAPI to Coq's CI so it would in theory be ready for each new release, however that'd add quite a burden for developers and I think the overhead tends to be much more than just updating the release once each 6 months.

**Comment by jhaag** [comment]
Out of curiosity, what is the process for adding a project to Coq's CI, and who is responsible for updating downstream breakages of packages which are registered with Coq's CI? Given how coupled SerAPI is with Coq's internals, has there been any discussion about upstreaming SerAPI to Coq?

At [BedRock](https://bedrocksystems.com/), we've really been enjoying [Alectryon](https://github.com/cpitclaudel/alectryon) (cc @cpitclaudel), but it's difficult to build out our documentation and content when we have to contend with intermittent breakages which extend for significant periods of time. I would be interested in working with you to determine whether there is a way that we can keep SerAPI and Coq more in lockstep.

**Comment by ejgallego** [comment]
> Out of curiosity, what is the process for adding a project to Coq's CI

Process is documented [here]() , basically I'd have to agree to submit it.

> and who is responsible for updating downstream breakages of packages which are registered with Coq's CI?

Usually the person that creates the breakage, with the help of package authors in some cases.

> Given how coupled SerAPI is with Coq's internals, has there been any discussion about upstreaming SerAPI to Coq?

Yes, there has been, and the conclusion was not to do it; it is a pity and indeed this would solve many problems, but let's say Coq is a very conservative project in terms of this kind of radical changes.

On the other hand, SerAPI is still a very experimental project so I'm wary of doing promises, not to say manpower these days is very limited.

> At [BedRock](https://bedrocksystems.com/), we've really been enjoying [Alectryon](https://github.com/cpitclaudel/alectryon) (cc @cpitclaudel), but it's difficult to build out our documentation and content when we have to contend with intermittent breakages which extend for significant periods of time. I would be interested in working with you to determine whether there is a way that we can keep SerAPI and Coq more in lockstep.

Thanks! I think the 3 main relevant issues as to keep SerAPI almost auto-updated to last Coq are:

- #82 , this is for example what is keeping 8.13 version from working, and it is the most painful step, as you need to scan manually for changed genars, and you won't realize you are missing one until you error out by finding that construction in your Coq program
- serialization: would be good if serlib would move to Coq itself, but indeed not even the current build system of Coq would support it; I have been working for more than 2 years trying to update such build system but the transition has been blocked so far and in general has been extremely painful
- Coq API, this tends to be quite easy, but you need to have an understanding of which API parts have changed upstream.

Generally, I'm afraid that the only option today to have a version of Coq that can provide some "advanced" features is to actually fork Coq, as the current development model simply lacks the resources and agility necessary as to make a lot of progress, in particular w.r.t. tooling. Technical debt in Coq itself tends to grow in each release as people add features more as a DIY effort than as a coordinated medium-term roadmap.

**Comment by ejgallego** [comment]
I've updated the first link to Coq's CI Readme as I typed it wrong.

**Comment by ejgallego** [comment]
Anyways, let's talk more on Zulip, I'm sure we can much improve the status quo.

**Comment by ejgallego** [comment]
Another pretty worrying problem is that `ppx_deriving` has a hard time with GADT, as we use more of these in Coq, the work here starts to go bad.

For the rest, this PR is ready, so CI-permitting will merge soon.

**Comment by ejgallego** [comment]
Made the default branch.

**Pull request closed without merging**
