### PR TITLE
[test] Add test for abstract tactic

### PR DESCRIPTION
**Pull request by palmskog**
This appears to be the last error when serializing/deserializing the Binary Rational Numbers Coq-contrib project.

### CODE REVIEW

**Comment by ejgallego** [comment]
That's a tricky one, the problem is that SerAPI loads the ssreflect plugin by default, which modifies the parser and makes that file invalid. The workaround is to add parenthesis in the:

```
abstract (let ... T_local)
```
line.

SerAPI will load plugins on-demand in the future, however I am not sure this is doable for 8.9 :S

**Comment by ejgallego** [comment]
Let's see how many more instances you find of this kind of bug; if it turns out to be pervasive we'll figure out a workaround.

**Comment by palmskog** [comment]
My impression is that the `abstract` tactic is rarely used, but I will keep an eye out for this problem. We will apply your workaround locally. Thanks!

**Comment by ejgallego** [comment]
> My impression is that the `abstract` tactic is rarely used, but I will keep an eye out for this problem. We will apply your workaround locally. Thanks!

The particular problem here is `abstract` followed by `let` so I expect this to be rare.

The thing is that the plugin registration mechanism of 8.9 is a bit too primitive for what we would like it to be for SerAPI, in particular we can know the name of the `cmxs` file being loaded, see `Mltop.load_obj`.

Maybe that should be enough for our purposes tho.

**Comment by ejgallego** [comment]
Note: I will fix this for 8.9 hopefully.

**Comment by ejgallego** [comment]
Ok, fix is on the way!

**Pull request merged**
