### PR TITLE
Add Coq8.6 link

### PR DESCRIPTION
**Pull request by zjhmale**
Discussed at #29.

### CODE REVIEW

**Comment by ejgallego** [comment]
I am inclined no to take this PR in full, SerAPI seems to work well for me in 8.6. Could you try again with 8.6?

**Comment by zjhmale** [comment]
Yes, I can build serapi with Coq8.6 now, should I close this?

**Comment by ejgallego** [comment]
Please, and thanks for testing! I'll add the mailing list information to the README ASAP, in case we want to discuss.

**Comment by zjhmale** [comment]
Cool, I also want to work on https://github.com/ejgallego/coq-serapi/issues/26, a mailing list will be great!
>Please, and thanks for testing! I'll add the mailing list information to the README ASAP, in case we want to discuss.

**Pull request merged**
