### PR TITLE
Adapt to coq/coq#16958 (removal of lazy_val)

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by ejgallego** [comment]
@ppedrot you should have merge rights, if you accepted the invite, can you try?

**Comment by ppedrot** [comment]
Should I just use the github merge interface?

**Comment by ejgallego** [comment]
> Should I just use the github merge interface?

Yup, or whatever other method you prefer.

**Comment by ppedrot** [comment]
Seems to have worked indeed.

**Comment by Zimmi48** [comment]
I have an issue since coq/coq#16958 was requested for backporting but not coq/coq#16930 for which an overlay was merged before. Therefore, I would need a `v8.17` branch to be created from f4883a3b7ac08208300fbc45bed10047d1ad9f38 or 353c9e9acdfc013ff36c17f2ae02d28decad2a76 with this PR backported (unless we renounce to backport coq/coq#16958 to `v8.17`).

**Comment by ejgallego** [comment]
Hi @Zimmi48 , will do the branch ASAP, thanks for the detailed information.

**Comment by ejgallego** [comment]
Branch is updated, CI doesn't pass as I've included some PRs that are not backported yet.

How would you like the branch to be setup w.r.t. backported PRs? I'll continue discussion on Zulip, but feel free to push to this repos as it better works for you.

**Comment by Zimmi48** [comment]
Thanks!
I will try to minimize the number of backported PRs that require overlays, as the rc1 is supposed to come out soon.

**Pull request merged**
