### PR TITLE
Adapt w.r.t. coq/coq#16773.

### PR DESCRIPTION
**Pull request by ppedrot**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Please merge now

**Comment by ppedrot** [comment]
pinging @ejgallego explicitly, the message might have been lost due to the previous draft status

**Review by ejgallego — APPROVED** [review]
Thanks

**Comment by ejgallego** [comment]
Thanks, will merge (or fix on my side and merge) after the CI run.

**Comment by ppedrot** [comment]
This seems to be ok.

**Pull request merged**
