### PR TITLE
adapt to coq/coq#16897

### PR DESCRIPTION
**Pull request by gares**

### CODE REVIEW

**Comment by ppedrot** [comment]
Please merge now.

**Comment by Zimmi48** [comment]
Could it be that you missed some parts that are still using the old API? The CI is showing a new failure related to this API change: https://github.com/ejgallego/coq-serapi/actions/runs/3583923361/jobs/6029943234. I didn't look deeply into it yet.

**Comment by ppedrot** [comment]
Are we only testing a subset of the full serapi test-suite on the Coq CI?

**Comment by ejgallego** [comment]
Sorry folks, indeed that CI problem is unrelated; will fix ASAP.

**Pull request merged**
