### PR TITLE
[sertop] Add `--mode=vo` option that will output a `.vo` file.

### PR DESCRIPTION
**Pull request by ejgallego**
This way we can do `.sexp -> .vo`.

### CODE REVIEW

**Comment by palmskog** [comment]
Just for the record, this looked great and appeared to work great. I was just waiting for some final tests from colleagues before approval, but we can report bugs if anything shows up instead.

**Comment by ejgallego** [comment]
Thanks @palmskog , the thing is that I had some big refactoring pending on this so I merged so I could push the code reorganization; in particular I was worried about the bad error printing / reporting we had.

The thing in HEAD now is not perfect but it should be better.

**Comment by ejgallego** [comment]
For example the error we got in the `abstract` test case was pretty bare.

**Comment by ejgallego** [comment]
Note that 329bfa4069e83c273460824debd83bf45b34f545 fixes an incomplete serialization of the attributes of the top-level vernacular. This may change the sexp format for you folks, even if I did a change entry.

But it is necessary in order to locate errors properly in some cases.

**Pull request merged**
