### PR TITLE
Adapt to coq/coq#16930 (remove Flags.native_compiler)

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
backwards compatible, please merge

**Comment by ejgallego** [comment]
@SkySkimmer you should be able to merge stuff by yourself now.

**Comment by SkySkimmer** [comment]
actually not backwards compatible

**Comment by ppedrot** [comment]
Please merge now.

**Comment by Zimmi48** [comment]
FYI this PR was put in milestone 0.17.0 but corresponding Coq PR was set for milestone 8.18+rc1.

**Pull request merged**
