### PR TITLE
adapt to coq/coq#16682

### PR DESCRIPTION
**Pull request by Alizter**

### CODE REVIEW

**Comment by Alizter** [comment]
@ejgallego I believe that this will be included in 8.17 FYI.

**Comment by ejgallego** [comment]
Thanks @Alizter , please feel free to adjust the milestone.

**Comment by jfehrle** [comment]
@ejgallego I merged Alitzer's Coq PR, would you merge this for me now?  (I don't know the procedure and may not have the permissions.). Thanks.

**Comment by ejgallego** [comment]
Thanks!

**Pull request merged**
